package wd

const (
	CUSTOMCONSTMODULE          = "module"
	CUSTOMCONSTOPTION          = "option"
	CUSTOMCONSTGJSONKEYS       = "gjsonkeys"
	CUSTOMCONSTRESPMSG         = "resp-msg"
	CUSTOMCONSTRESPSTATUS      = "resp-status"
	CUSTOMCONSTSKIP            = "skip"
	CUSTOMCONSTONLYREQ         = "only-req"
	CUSTOMCONSTBRIEF           = "brief"
	CUSTOMCONSTNORECORD        = "no_record"
	CUSTOMCONSTREQUESTTIME     = "request_time"
	CUSTOMCONSTORIGINHEADER    = "Origin"
	CUSTOMCONSTEXCELTAG        = "excel"
	CUSTOMCONSTJSONTAG         = "json"
	CUSTOMCONSTZHLOCALE        = "zh"
	CUSTOMCONSTTRACEIDHEADER   = "Trace-ID"
	CUSTOMCONSTJWTPAYLOAD      = "JWT_PAYLOAD"
	CUSTOMCONSTJWTTOKEN        = "JWT_TOKEN"
	CUSTOMCONSTAPPLICATIONJSON = "application/json"
	CUSTOMCONSTLATENCYMSINFO   = "latency_ms_info"
	CUSTOMCONSTDURATIONMS      = "duration_ms"
	CUSTOMCONSTSTATUSCODE      = "status_code"
	CUSTOMCONSTRESPINFO        = "resp_info"
	CUSTOMCONSTREQINFO         = "req_info"
)
